---
###################################################################
# Travis Build for docker image test - yabhinav/zeppelin        ###
# Author : Abhinav Y <http://yabhinav.github.io>                ###
###################################################################
sudo: required
language: python
python: "2.7"
services:
  - docker

git:
  depth: 10

before_install:
    - sudo apt-get update
    # Install/Upgrade latest Git and docker community engine
    - sudo apt-get install --only-upgrade git docker-ce

script:
    - docker version
    - ./docker-ci.sh build
    - ./docker-ci.sh run latest zeppelin
    - ./docker-ci.sh status latest zeppelin
    - ./docker-ci.sh cleanup zeppelin

# send notification to ansible-galaxy on build failure/change on release branch
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
